language: ruby
rvm:
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: tTmCIniGFgReS0iOsB2WKn2l2ZUZTko2cFLwVo8jIILlEuNy0ijKIchNARY07wfoRoM/vgp1whsh+QBsqoCd97ajLyNFTaTR1b41AeNhdueemVtXK17DJmLIEeSh1EV+b5HU8xHo86KX/lYbn0zTxtJlSj6McuJXpI88eUGg8dULflJqvc2Y2vVM+/t0JwdQse3czUcuS9SMD+2fKkMCiC8opDmSHgxTXMlDwgxz6RLJcK5eU1f+RYYkbKoTHpnsQP1CC3V+9nMd3ETv2jYEqBya/wkWXMFbohfvYlU9TQ6SOGg3QDGCEP+NUDIw2aXQQsiFnsHHmn5bvneUCqxwtIlBrKNARQi9+g24yzx4TS4020+ofBVpPD+myhaJ1T5MPoLtAFsxmySxgUvM/1YdooQepOb3U5amV0ZnPwjyY/yTlftBnyro4DrkzLGZfH7phum30/Q76qbCLoTUicHZuGBnMoiUZxtiX+7x0OCt8YOKAy0AwUinsluzWNeQx0ZKlGpyA7h0Tupgz7+5YtBvjs9FrTOdh7YRjmauYQMnkT4SDPxdqr+5UxNjdhGCJlq/3AUdzHRBGWh+nduUAqam6TZ3WdoXJr90zE4qZOGjzZi6R9gOuX5Ea6ECHWTfi+UGeiLA/Gk/crpoDajuhZVLD9+CtnoQgbS/EIklhJ0bH8Y=
  app:  guarded-tundra-95985
  on:
    repo: Aurelien-Py/projet
